server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri:
            http://localhost:8123
          predicates:
            - Path=/api/**
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  metadata-report:
    address: nacos://127.0.0.1:8848