server:
  port: 8090

spring:
  application:
    name: panda-api-gateway
  redis:
    host: localhost
    database: 0
  #    password: 123456
  cloud:
    gateway:
      routes:
        - id: api_route
          uri:
            http://localhost:8123
          predicates:
            - Path=/api/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: panda-api-gateway
  #    qos-enable: true
  #    qos-port: 33333
  #    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
