server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri:
            http://localhost:8123
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: dubbo-springboot-consumer
    protocol:
      name: dubbo
      port: -1
    registry:
      id: nacos-registry
      address: nacos://127.0.0.1:8848
